@startuml
usecase "Программирование"
usecase "Императивное"
usecase "Декларативное"
usecase "Структурное"
usecase "Не структурное"
usecase "Процедурное"
usecase "Объектно-ориентированное"
usecase "Функциональное"
usecase "Логическое"
usecase "На основе классов"
usecase "Прототипное"
usecase "Аппликативное"
usecase "Комбинаторное"

"Программирование" --> "Декларативное"
"Программирование" --> "Императивное"
"Декларативное" --> "Логическое"
"Декларативное" --> "Функциональное"
"Функциональное" --> "Аппликативное"
"Функциональное" --> "Комбинаторное"
"Императивное" --> "Структурное"
"Императивное" --> "Не структурное"
"Структурное" --> "Процедурное"
"Структурное" --> "Объектно-ориентированное"
"Структурное" ..> "Функциональное"
"Объектно-ориентированное" --> "На основе классов"
"Объектно-ориентированное" --> "Прототипное"
@enduml